:concurrency: 5
:pidfile: ./tmp/sidekiq.pid
:logfile: ./log/sidekiq.log
:verbose: true

:queues:
  - default
  - [jianggaowang, 3]
  - [previews_upload, 2]
  - [remote_file_delete, 1]

development:
  :concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 5
